HISTORICAL_COMPLAINTS = [
    {
        "id": 101,
        "complaint_number": "CMP-2025-0042",
        "product_name": "Paracetamol Tablets 500mg (FDF)",
        "batch_number": "PARA-2401",
        "dosage_form": "FDF",
        "complaint_category": "Physical Defect",
        "severity": "Minor",
        "complainant_name": "Metro City Hospital Pharmacy",
        "complainant_type": "Hospital",
        "complaint_date": "2025-11-14",
        "description": "Blister pack contained tablets with slight edge chipping and laminating. No foreign matter observed.",
    },
    {
        "id": 102,
        "complaint_number": "CMP-2025-0089",
        "product_name": "Metformin Hydrochloride Active Pharmaceutical Ingredient (API)",
        "batch_number": "MET-API-8812",
        "dosage_form": "API",
        "complaint_category": "Contamination/Foreign Matter",
        "severity": "Critical",
        "complainant_name": "BioHealth Formulations Ltd",
        "complainant_type": "Manufacturer",
        "complaint_date": "2025-12-05",
        "description": "Black specks identified in drum #3 of 25kg fiber drum packaging during incoming quality inspection.",
    },
    {
        "id": 103,
        "complaint_number": "CMP-2026-0004",
        "product_name": "Amoxicillin and Clavulanate Potassium Oral Suspension 228.5mg/5mL",
        "batch_number": "AMX-9943",
        "dosage_form": "FDF",
        "complaint_category": "Dissolution/Efficacy",
        "severity": "Major",
        "complainant_name": "St. Jude Pediatric Clinic",
        "complainant_type": "Clinic",
        "complaint_date": "2026-01-18",
        "description": "Powder failed to reconstitute smoothly upon adding purified water; persistent caking at the bottom of bottle.",
    },
    {
        "id": 104,
        "complaint_number": "CMP-2026-0012",
        "product_name": "Atorvastatin Calcium 20mg Film-Coated Tablets",
        "batch_number": "ATV-2602",
        "dosage_form": "FDF",
        "complaint_category": "Packaging",
        "severity": "Minor",
        "complainant_name": "CarePlus Wholesale Distributors",
        "complainant_type": "Distributor",
        "complaint_date": "2026-02-02",
        "description": "Secondary carton glue failed, causing cartons to open in transit. Blisters remained intact.",
    },
    {
        "id": 105,
        "complaint_number": "CMP-2026-0019",
        "product_name": "Ceftriaxone for Injection USP 1g Sterile Powder",
        "batch_number": "CEF-7731",
        "dosage_form": "FDF",
        "complaint_category": "Contamination/Foreign Matter",
        "severity": "Critical",
        "complainant_name": "Apex Critical Care Center",
        "complainant_type": "Hospital",
        "complaint_date": "2026-02-20",
        "description": "Visible particulate matter suspended in vial after reconstitution with sterile water for injection.",
    }
]
